
services:
  flask_api:
    build: ./backend
    container_name: flask_api
    ports:
      - "5000:5000"
    restart: always
    networks:
      - app_network

  vue_frontend:
    build: ./frontend
    container_name: vue_frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - flask_api
    networks:
      - app_network

networks:
  app_network:
    driver: bridge